In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/pima-indians-diabetes-database/diabetes.csv


In [2]:
import pandas as pd
df = pd.read_csv('/kaggle/input/pima-indians-diabetes-database/diabetes.csv')
print(df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [3]:
df.columns = ["pregnancies", "glucose", "blood_pressure", "skin_thickness","insulin","bmi","Diabetes_Pedigree_Function","age","outcome"]
df.head()

pregnancies  glucose  blood_pressure  skin_thickness  insulin   bmi  \
0            6      148              72              35        0  33.6   
1            1       85              66              29        0  26.6   
2            8      183              64               0        0  23.3   
3            1       89              66              23       94  28.1   
4            0      137              40              35      168  43.1   

   Diabetes_Pedigree_Function  age  outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
pregnancies                   768 non-null int64
glucose                       768 non-null int64
blood_pressure                768 non-null int64
skin_thickness                768 non-null int64
insulin                       768 non-null int64
bmi                           768 non-null float64
Diabetes_Pedigree_Function    768 non-null float64
age                           768 non-null int64
outcome                       768 non-null int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
df.describe().T

count        mean         std     min       25%  \
pregnancies                 768.0    3.845052    3.369578   0.000   1.00000   
glucose                     768.0  120.894531   31.972618   0.000  99.00000   
blood_pressure              768.0   69.105469   19.355807   0.000  62.00000   
skin_thickness              768.0   20.536458   15.952218   0.000   0.00000   
insulin                     768.0   79.799479  115.244002   0.000   0.00000   
bmi                         768.0   31.992578    7.884160   0.000  27.30000   
Diabetes_Pedigree_Function  768.0    0.471876    0.331329   0.078   0.24375   
age                         768.0   33.240885   11.760232  21.000  24.00000   
outcome                     768.0    0.348958    0.476951   0.000   0.00000   

                                 50%        75%     max  
pregnancies                   3.0000    6.00000   17.00  
glucose                     117.0000  140.25000  199.00  
blood_pressure               72.0000   80.00000  122.00  
skin_thickness               23.0000   32.00000   99.00  
insulin                      30.5000  127.25000  846.00  
bmi                          32.0000   36.60000   67.10  
Diabetes_Pedigree_Function    0.3725    0.62625    2.42  
age                          29.0000   41.00000   81.00  
outcome                       0.0000    1.00000    1.00

Columns like **Glucose,blood_pressure,skin_thickness,Insulin & bmi** have min value as 0 which does not seem to be a valid value for these attributes so replace these values with atrribute mean values

In [7]:
for cols in ['glucose','blood_pressure','skin_thickness','insulin','bmi']:
    df.loc[df[cols] == 0,cols]= df[cols].mean(skipna=True)

In [8]:
df.describe().T

count        mean        std     min        25%  \
pregnancies                 768.0    3.845052   3.369578   0.000   1.000000   
glucose                     768.0  121.681605  30.436016  44.000  99.750000   
blood_pressure              768.0   72.254807  12.115932  24.000  64.000000   
skin_thickness              768.0   26.606479   9.631241   7.000  20.536458   
insulin                     768.0  118.660163  93.080358  14.000  79.799479   
bmi                         768.0   32.450805   6.875374  18.200  27.500000   
Diabetes_Pedigree_Function  768.0    0.471876   0.331329   0.078   0.243750   
age                         768.0   33.240885  11.760232  21.000  24.000000   
outcome                     768.0    0.348958   0.476951   0.000   0.000000   

                                   50%        75%     max  
pregnancies                   3.000000    6.00000   17.00  
glucose                     117.000000  140.25000  199.00  
blood_pressure               72.000000   80.00000  122.00  
skin_thickness               23.000000   32.00000   99.00  
insulin                      79.799479  127.25000  846.00  
bmi                          32.000000   36.60000   67.10  
Diabetes_Pedigree_Function    0.372500    0.62625    2.42  
age                          29.000000   41.00000   81.00  
outcome                       0.000000    1.00000    1.00

In [9]:
df.corr()

pregnancies   glucose  blood_pressure  \
pregnancies                    1.000000  0.127964        0.208984   
glucose                        0.127964  1.000000        0.219666   
blood_pressure                 0.208984  0.219666        1.000000   
skin_thickness                 0.013376  0.160766        0.134155   
insulin                       -0.018082  0.396597        0.010926   
bmi                            0.021546  0.231478        0.281231   
Diabetes_Pedigree_Function    -0.033523  0.137106        0.000371   
age                            0.544341  0.266600        0.326740   
outcome                        0.221898  0.492908        0.162986   

                            skin_thickness   insulin       bmi  \
pregnancies                       0.013376 -0.018082  0.021546   
glucose                           0.160766  0.396597  0.231478   
blood_pressure                    0.134155  0.010926  0.281231   
skin_thickness                    1.000000  0.240361  0.535703   
insulin                           0.240361  1.000000  0.189856   
bmi                               0.535703  0.189856  1.000000   
Diabetes_Pedigree_Function        0.154961  0.157806  0.153508   
age                               0.026423  0.038652  0.025748   
outcome                           0.175026  0.179185  0.312254   

                            Diabetes_Pedigree_Function       age   outcome  
pregnancies                                  -0.033523  0.544341  0.221898  
glucose                                       0.137106  0.266600  0.492908  
blood_pressure                                0.000371  0.326740  0.162986  
skin_thickness                                0.154961  0.026423  0.175026  
insulin                                       0.157806  0.038652  0.179185  
bmi                                           0.153508  0.025748  0.312254  
Diabetes_Pedigree_Function                    1.000000  0.033561  0.173844  
age                                           0.033561  1.000000  0.238356  
outcome                                       0.173844  0.238356  1.000000

None of the attributes shown correlation between them. Maximum correlation is between Skin_thickenss and bmi (0.535684).
Outcome has maximum correlation with glucose (0.492206)

In [10]:
from sklearn.model_selection import train_test_split
Y = df['outcome']
X = df.drop(columns=['outcome'])


X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=1)

print('X_train size {} , X_test size {}'.format(X_train.shape,X_test.shape))

X_train size (537, 8) , X_test size (231, 8)


In [11]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(criterion='entropy',random_state=1)

dtc.fit(X_train,y_train)
print('Accuracy on train data:',dtc.score(X_train,y_train))
print('Accuracy on test data:',dtc.score(X_test,y_test))

from sklearn.metrics import confusion_matrix,f1_score
y_pred_dtc = dtc.predict(X_test)
dtc_cm = confusion_matrix(y_test,y_pred_dtc)
print('Confusion Matrix\n {}'.format(dtc_cm))

f1score_dtc = f1_score(y_test,y_pred_dtc)
print('F1 Score for Decision Tree:',f1score_dtc)

Accuracy on train data: 1.0
Accuracy on test data: 0.7316017316017316
Confusion Matrix
 [[113  33]
 [ 29  56]]
F1 Score for Decision Tree: 0.6436781609195402


In [12]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=100,criterion='gini',min_samples_split=5,min_samples_leaf=5,
                             max_features='auto',random_state=1)
rfc.fit(X_train,y_train)
print('Accuracy on train data:',rfc.score(X_train,y_train))
print('Accuracy on test data:',rfc.score(X_test,y_test))
y_pred_rfc = rfc.predict(X_test)
rfc_cm = confusion_matrix(y_test,y_pred_rfc)
print('Confusion Matrix\n {}'.format(rfc_cm))

f1score_rfc = f1_score(y_test,y_pred_rfc)
print('F1 Score for RandomForest:',f1score_rfc)

Accuracy on train data: 0.9124767225325885
Accuracy on test data: 0.7792207792207793
Confusion Matrix
 [[129  17]
 [ 34  51]]
F1 Score for RandomForest: 0.6666666666666665


In [13]:
from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier(n_estimators=110,learning_rate=1,random_state=1)
abc.fit(X_train,y_train)

print('Accuracy on train data:',abc.score(X_train,y_train))
print('Accuracy on test data:',abc.score(X_test,y_test))
y_pred_abc = abc.predict(X_test)
abc_cm = confusion_matrix(y_test,y_pred_abc)
print('Confusion Matrix\n {}'.format(abc_cm))

f1score_abc = f1_score(y_test,y_pred_abc)
print('F1 Score for AdaBoost:',f1score_abc)

Accuracy on train data: 0.8677839851024208
Accuracy on test data: 0.7835497835497836
Confusion Matrix
 [[126  20]
 [ 30  55]]
F1 Score for AdaBoost: 0.6875


In [14]:
from sklearn.ensemble import BaggingClassifier

bgc = BaggingClassifier(n_estimators=100,max_samples=0.7,max_features=0.5,random_state=1)
bgc.fit(X_train,y_train)
print('Accuracy for train data {}'.format(bgc.score(X_train,y_train)))
print('Accuracy for test data {}'.format(bgc.score(X_test,y_test)))
y_pred_bgc = bgc.predict(X_test)
bgc_cm = confusion_matrix(y_test,y_pred_bgc)
print('Confusion Matrix\n {}'.format(bgc_cm))

f1score_bgc = f1_score(y_test,y_pred_bgc)
print('F1 Score for BaggingClassifier:',f1score_bgc)

Accuracy for train data 0.9981378026070763
Accuracy for test data 0.7792207792207793
Confusion Matrix
 [[130  16]
 [ 35  50]]
F1 Score for BaggingClassifier: 0.6622516556291391


In [15]:
from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier(loss='deviance',learning_rate=0.1, n_estimators=90,subsample=0.8,
                                criterion="friedman_mse",min_samples_split=0.2,min_samples_leaf=5,max_depth=3,random_state=1)
gbc.fit(X_train,y_train)
print('Accuracy for train data {}'.format(gbc.score(X_train,y_train)))
print('Accuracy for test data {}'.format(gbc.score(X_test,y_test)))
y_pred_gbc = gbc.predict(X_test)
gbc_cm = confusion_matrix(y_test,y_pred_gbc)
print('Confusion Matrix\n {}'.format(gbc_cm))

f1score_gbc = f1_score(y_test,y_pred_gbc)
print('F1 Score for GradientBoostingClassifier:',f1score_gbc)

Accuracy for train data 0.8696461824953445
Accuracy for test data 0.8051948051948052
Confusion Matrix
 [[128  18]
 [ 27  58]]
F1 Score for GradientBoostingClassifier: 0.7204968944099379


In [16]:
print('F1 Score for Decision Tree:',f1score_dtc)
print('F1 Score for RandomForest:',f1score_rfc)
print('F1 Score for AdaBoost:',f1score_abc)
print('F1 Score for BaggingClassifier:',f1score_bgc)
print('F1 Score for GradientBoostingClassifier:',f1score_gbc)

F1 Score for Decision Tree: 0.6436781609195402
F1 Score for RandomForest: 0.6666666666666665
F1 Score for AdaBoost: 0.6875
F1 Score for BaggingClassifier: 0.6622516556291391
F1 Score for GradientBoostingClassifier: 0.7204968944099379


## GradientBoostingClassifier is the alogrithm with maximum F1 score of 0.7204
 ## Normal DecisionTree has score of 0.643 and with ensemble techniques it increased to 0.7204